# --- UI Service Config ---
quarkus.http.port=7075
quarkus.rest-client.product-api.url=http://localhost:7071

# --- OIDC Production Config ---
quarkus.oidc.enabled=true
quarkus.oidc.application-type=web-app

# ???????? ?????? ?????? ?????? Keycloak (???? 9090, ????? vape-realm)
quarkus.oidc.auth-server-url=http://localhost:9090/realms/vape-realm
quarkus.oidc.client-id=vape-client
quarkus.oidc.credentials.secret=secret

# ?? ??????? ???????????? ?????? Dev Services (?? ?? ??? ??????? ???? Docker)
quarkus.keycloak.devservices.enabled=false

quarkus.oidc.logout.path=/logout
quarkus.oidc.logout.post-logout-path=/