version: '3.8'

services:
  # База даних для Keycloak (щоб налаштування не зникали після перезапуску)
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Сам Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: vape-keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      # Ми використовуємо порт 9090, щоб не конфліктувати з іншими сервісами
      - "9090:8080"
    depends_on:
      - keycloak-db
    volumes:
      # Ця папка знадобиться, якщо ми захочемо зберегти налаштування реалму
      - ./keycloak-config:/opt/keycloak/data/import
  # База даних для Product Service
  product-db:
    image: postgres:15
    container_name: product-db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345  # <--- ВАШ НОВИЙ ПАРОЛЬ
    ports:
      - "5433:5432"

  # База даних для Inventory Service (MongoDB)
  mongo-db:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"

  # База даних для Order Service (Repository Pattern)
  order-db:
      image: postgres:15
      container_name: order-db
      environment:
        POSTGRES_DB: order_db
        POSTGRES_USER: user
        POSTGRES_PASSWORD: 12345
      ports:
        - "5434:5432" # Використовуємо порт 5434, щоб не конфліктував з іншими
volumes:
  keycloak_data: