# --- Order Service Config ---
quarkus.http.port=7074
# ???????? ?????????? gRPC ??????, ??? ?? ???? ????????? ?? 9000
quarkus.grpc.server.port=7075

# --- ?????? ?? Product Service (7071) ---
quarkus.rest-client.product-api.url=http://localhost:7071

# --- ?????? ?? Inventory Service (7073) ---
quarkus.grpc.clients.inventory-service.host=localhost
quarkus.grpc.clients.inventory-service.port=7073
quarkus.grpc.clients.inventory-service.plain-text=true

# --- PostgreSQL Config ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=12345
# ???????? ????? ?? ???? 5434
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/order_db?options=-c%20timezone=UTC

# ????????? ???????
quarkus.hibernate-orm.database.generation=drop-and-create