# --- Order Service Config ---
quarkus.http.port=7070

# ???????? ?????????? gRPC ??????, ??? ?? ???? ????????? ?? 9000
quarkus.grpc.server.port=7074

# --- ?????? ?? Product Service (7071) ---
quarkus.rest-client.product-api.url=http://localhost:7071

# --- ?????? ?? Inventory Service (7073) ---
quarkus.grpc.clients.inventory-service.host=localhost
quarkus.grpc.clients.inventory-service.port=7073
quarkus.grpc.clients.inventory-service.plain-text=true